### ISSUE TITLE
Need to filter variants based on availability for all queried experiments

### ISSUE THREAD

**Issue by Timh37** [Timh37/CMIP6cex#6]
Querying multiple experiments, like `experiment_id = ['historical','ssp585']`, will yield all variants available for each respective experiment. However, the variants of 'historical' that are not available for 'ssp585' may not be desired, so it would be good to filter these out before the analysis.

One way to do so may be to match datasets on all attributes except for `experiment_id`, and then throw out variants that do not have all `experiment_id`'s.

**Comment by jbusecke** [comment]
try 
```python
.search(
    ...,
    require_all_on=['source_id', 'member_id'],
)
```

That makes sure that all experiments are given for a single member/source combination.

**Comment by Timh37** [comment]
Perfect!
