### ISSUE TITLE
`xmip`'s `combined_preprocessing` raises `Renaming failed` warnings

### ISSUE THREAD

**Issue by Timh37** [Timh37/CMIP6cex#7]
`xmip`'s `combined_preprocessing` fails to rename variables, for example:

```python
my_models = ['MPI-ESM1-2-HR']
col = google_cmip_col()
experiment_id='ssp585'
source_id = my_models
kwargs = {
    'zarr_kwargs':{
        'consolidated':True,
        'use_cftime':True
    },
    'aggregate':False
}

cat_data = col.search(
    source_id=source_id,
    experiment_id=['historical','ssp585'],
    table_id='day',
    variable_id=['psl','sfcWind'],
    member_id=['r1i1p1f1','r2i1p1f1'],
    require_all_on=['source_id', 'member_id','grid_label']
)

ddict = cat_data.to_dataset_dict(**kwargs,preprocess=combined_preprocessing)
```

results in: 
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/55179716/216373283-ddef51ef-b59b-4ef2-b3c5-7c2088d185d8.png">

**Comment by jbusecke** [comment]
Yeah these are not great. I recently worked on [this](https://github.com/jbusecke/xMIP/pull/280) but am not entirely happy with it yet. Can you confirm the version you are using?

**Comment by jbusecke** [comment]
The ones above do not necessarily indicate failure though! Often this is triggered if there a two different dimensions/coordinates that xmip tries to rename into the same thing.

**Comment by Timh37** [comment]
No longer relevant.
